# Generated by Django 4.1.4 on 2022-12-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewtable',
            field=models.BooleanField(default=True),
        ),
    ]
